#!/usr/bin/env python3
"""Generate verification/STATUS.md — the at-a-glance verification view.

One row per catalog pattern: verdict, score, naming alignment, last checked,
naming recommendation, and the human decision. Pure derived data, assembled
from patterns.yaml, experiments/README.md, verification/evidence/, and
verification/DECISIONS.md. Run with --check to fail (exit 1) when the
committed file is stale — the same contract as generate-patterns-data.py.
"""

import argparse
import datetime
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent.parent
STATUS_PATH = REPO_ROOT / "verification" / "STATUS.md"
EVIDENCE_DIR = REPO_ROOT / "verification" / "evidence"
DECISIONS_PATH = REPO_ROOT / "verification" / "DECISIONS.md"
STALE_AFTER_DAYS = 90

EXPERIMENT_ROW_RE = re.compile(
    r"^\|\s*\*\*\[([^\]]+)\]\(#([a-z0-9-]+)\)\*\*\s*\|\s*(?:Beginner|Intermediate|Advanced)\s*\|")

HEADER = """\
# Verification Status

At-a-glance verification state of every pattern. Generated by
`scripts/generate-verification-status.py` from `verification/evidence/` and
[DECISIONS.md](DECISIONS.md) — do not hand-edit; CI fails when this file is stale.

"""


def configure_repo_root(root):
    """Point all derived inputs/outputs at a repository checkout."""
    global REPO_ROOT, STATUS_PATH, EVIDENCE_DIR, DECISIONS_PATH
    REPO_ROOT = Path(root).resolve()
    STATUS_PATH = REPO_ROOT / "verification" / "STATUS.md"
    EVIDENCE_DIR = REPO_ROOT / "verification" / "evidence"
    DECISIONS_PATH = REPO_ROOT / "verification" / "DECISIONS.md"

LEGEND = """\
**Assessed** means an evidence file exists; it does not mean the verdict is `verified`.
**Verdict** — `verified`: complete v2 provenance, at least 8 points from T1-T4, a shipped implementation,
and independent practitioner adoption · `weak`: assessed evidence exists but is below that
bar or still has legacy provenance · `unverified`: no meaningful scored evidence (score <= 2) ·
`pending`: no assessment exists. **Freshness** — `current`: checked within 90 days ·
`stale`: last checked more than 90 days ago · `needs refresh`: migrated evidence lacks the
complete search and content provenance required for verification. Stale and needs-refresh
counts overlap the verdict counts.
**Score** — 0-45, the sum of source-tier weights (T1 shipped tool = 5 ... T5 social
mention = 1, at most 3 entries per tier). **Naming** — `strong`: most sources use our
name · `weak`: some do · `aliased`: industry uses other stable names (rename signal) ·
`none`: sources practice the mechanism without naming it.
Rules: [README.md](README.md) · recommendations and decisions: [DECISIONS.md](DECISIONS.md).

## How to refresh

- **This table only** (after evidence or DECISIONS.md changes):
  `python3 scripts/generate-verification-status.py`
- **Refresh evidence** (new evidence, new verdicts): run the pipeline — see
  "Running a verification" in [README.md](README.md). Quick versions:
  `/verify-patterns` in Claude Code from the repo root, or
  `gh workflow run verify-patterns.yml` (GitHub Actions plans weekly; every paid run attempt waits
  for protected-environment human approval before provider preflight or research).
"""


def load_main_patterns():
    """Return [(name, slug)] from patterns.yaml in catalog order."""
    registry = yaml.safe_load((REPO_ROOT / "patterns.yaml").read_text(encoding="utf-8"))
    return [(p["name"], p["id"]) for p in registry.get("patterns") or []]


def load_experimental_patterns():
    """Return [(name, slug)] from the experiments reference table in order."""
    patterns = []
    for line in (REPO_ROOT / "experiments" / "README.md").read_text(
            encoding="utf-8").splitlines():
        row = EXPERIMENT_ROW_RE.match(line)
        if row:
            patterns.append((row.group(1), row.group(2)))
    return patterns


def load_evidence(slug):
    """Return the evidence dict for a slug, or None when not yet assessed."""
    path = EVIDENCE_DIR / f"{slug}.yaml"
    if not path.is_file():
        return None
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def load_ledger():
    """Map pattern name -> (recommendation, decision) from the DECISIONS ledger."""
    ledger = {}
    if not DECISIONS_PATH.is_file():
        return ledger
    for line in DECISIONS_PATH.read_text(encoding="utf-8").splitlines():
        cells = [cell.strip() for cell in line.split("|")]
        if len(cells) < 7 or cells[1] in ("Pattern", "") or set(cells[1]) <= {"-"}:
            continue
        recommendation = cells[4].replace("**", "").split(" (")[0].strip()
        decision = cells[5].split(" —")[0].strip()
        ledger[cells[1]] = (recommendation, decision)
    return ledger


def parse_iso_date(value):
    """Return a date for a valid YAML/string ISO date, otherwise None."""
    try:
        return datetime.date.fromisoformat(str(value))
    except (TypeError, ValueError):
        return None


def evidence_freshness(evidence, today=None):
    """Return current, stale, or needs refresh for an assessed evidence file."""
    if evidence.get("provenance_status") != "complete":
        return "needs refresh"
    checked = parse_iso_date(evidence.get("last_checked"))
    if checked is None:
        return "needs refresh"
    today = today or datetime.date.today()
    if (today - checked).days > STALE_AFTER_DAYS:
        return "stale"
    return "current"


def summarize_patterns(patterns, today=None):
    """Count coverage, verdicts, and overlapping freshness states."""
    counts = {
        "assessed": 0,
        "verified": 0,
        "weak": 0,
        "unverified": 0,
        "pending": 0,
        "stale": 0,
        "needs refresh": 0,
    }
    for _, slug in patterns:
        evidence = load_evidence(slug)
        if evidence is None:
            counts["pending"] += 1
            continue
        counts["assessed"] += 1
        verdict = evidence.get("verdict")
        if verdict in ("verified", "weak", "unverified"):
            counts[verdict] += 1
        freshness = evidence_freshness(evidence, today)
        if freshness in ("stale", "needs refresh"):
            counts[freshness] += 1
    return counts


def format_row(name, slug, ledger, today=None):
    """Format one table row for a pattern."""
    evidence = load_evidence(slug)
    if evidence is None:
        return f"| {name} | pending | — | — | — | — | — | — |"
    checked = evidence.get("last_checked") or "—"
    freshness = evidence_freshness(evidence, today)
    recommendation, decision = ledger.get(name, ("—", "—"))
    return (f"| {name} | {evidence.get('verdict', '—')} "
            f"| {evidence.get('adoption_score', '—')} "
            f"| {evidence.get('naming_alignment', '—')} | {checked} | {freshness} "
            f"| {recommendation} | {decision} |")


def render_table(title, patterns, ledger, today=None):
    """Render one markdown table section for a pattern list."""
    counts = summarize_patterns(patterns, today)
    summary = (
        f"{counts['assessed']} of {len(patterns)} assessed: "
        f"{counts['verified']} verified · {counts['weak']} weak · "
        f"{counts['unverified']} unverified · {counts['pending']} pending · "
        f"{counts['stale']} stale · {counts['needs refresh']} need refresh"
    )
    lines = [f"## {title} ({summary})", "",
             "| Pattern | Verdict | Score | Naming | Last checked | Freshness "
             "| Recommendation | Decision |",
             "|---------|---------|-------|--------|--------------|-----------"
             "|----------------|----------|"]
    lines += [format_row(name, slug, ledger, today) for name, slug in patterns]
    return "\n".join(lines) + "\n\n"


def render_status(today=None):
    """Render the full STATUS.md content."""
    ledger = load_ledger()
    body = HEADER
    body += render_table("Main catalog", load_main_patterns(), ledger, today)
    body += render_table("Experimental", load_experimental_patterns(), ledger, today)
    body += LEGEND
    return body


def main():
    """Write STATUS.md, or with --check verify the committed copy is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if verification/STATUS.md is out of date")
    parser.add_argument(
        "--root", type=Path, default=REPO_ROOT,
        help="Repository checkout whose evidence/status should be generated")
    args = parser.parse_args()
    configure_repo_root(args.root)
    content = render_status()
    if args.check:
        current = STATUS_PATH.read_text(encoding="utf-8") if STATUS_PATH.is_file() else ""
        if current != content:
            print("verification/STATUS.md is out of date. "
                  "Run: python3 scripts/generate-verification-status.py")
            return 1
        print("verification/STATUS.md is up to date")
        return 0
    STATUS_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {STATUS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
